baseURL = "https://example.com/"
languageCode = "en-us"
title = "ZeroClutter Anime"
enableRobotsTXT = true

[pagination]
  pagerSize = 15

[params]
  description = "No clutter anime guides"
  author = "ZeroClutter Anime Team"

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "daily"
  priority = 0.8

[markup.goldmark.renderer]
  unsafe = true
